name: Build, Lint and Test CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install And Lint
        run: yarn install && yarn run lint
        env:
          CI: true
      - name: Build And Test
        run: yarn build && yarn test
        env:
          CI: true
